compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

# 7 dager: 10080
# 4 dager: 5760
# 2 dager: 2880
# 1 dag: 1440

npmMinimalAgeGate: 2880

npmPreapprovedPackages:
  - "@navikt/*"
  - react-router-dom@7.12.0
  - react-router@7.12.0
  - hono@4.11.4

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
