name: "Deploy dev"
on:
    push:
        branches:
            - "dev-*"
            - "main"
    workflow_dispatch:

jobs:
    build:
        name: "build"
        runs-on: "ubuntu-latest"

        permissions:
            contents: "read"
            id-token: "write"
            packages: "write"

        env:
            YARN_NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

        steps:
            - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" #v7

            - uses: "actions/setup-node@820762786026740c76f36085b0efc47a31fe5020" #v7
              with:
                  node-version: 24
                  cache: "yarn"

            - name: "Install dependencies"
              run: "yarn install --immutable"

            - name: "Build application"
              run: "yarn build"
              env:
                  ASTRO_KEY: ${{ secrets.ASTRO_KEY }}

            - name: "Prune devDependencies"
              run: "npm prune --omit=dev --legacy-peer-deps"

            - name: "Upload to cdn"
              uses: nais/deploy/actions/cdn-upload/v2@1de80da70ad26556ecdc5964a8b7ec3bbed98120 # master
              with:
                  team: dusseldorf
                  source: ./dist/client/_astro
                  destination: "ungdomsprogramytelse-innsyn-mikrofrontend-ssr"

            - name: "Build and push"
              uses: nais/docker-build-push@0e73849f69ff260ee27597553c0a7848ca4e9795 # v0
              id: docker-build-push
              with:
                  team: dusseldorf

        outputs:
            image: ${{ steps.docker-build-push.outputs.image }}

    update-manifest-dev:
        uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v3.yaml@71678a4147620d62d582b57fe30e1527b4add74f # main
        needs: build
        permissions:
            contents: "read"
        with:
            id: "ungdomsprogramytelse-innsyn"
            url: "http://ungdomsprogramytelse-innsyn-mikrofrontend-ssr.dusseldorf"
            appname: "ungdomsprogramytelse-innsyn-mikrofrontend-ssr"
            namespace: "dusseldorf"
            cluster: dev-gcp
            commitmsg: ${{ github.event.head_commit.message}}
            fallback: "fallback"
            ssr: true
        secrets: inherit

    deploy-dev:
        runs-on: "ubuntu-latest"
        permissions:
            contents: "read"
            id-token: "write"
        needs: [build, update-manifest-dev]
        steps:
            - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7
            - name: "Deploy to dev"
              uses: "nais/deploy/actions/deploy@1de80da70ad26556ecdc5964a8b7ec3bbed98120" # v2
              env:
                  CLUSTER: dev-gcp
                  RESOURCE: nais/dev-gcp/nais.yaml
                  VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}
